### PR TITLE
When reading mtx, produce float32 values, consistent with .tsv.gz. 

### LINKED ISSUE #183: Exporting mtx format, strange gene values
Hi,

I've exported matrix from Seurat as .mtx format for the first time, and the resulting gene values in cellbrowser look completely strange.
Screen Shot 2020-06-29 at 11 48 49
I've checked the .mtx file manually, the values there seem ok, so I guess it's either in the `.bin` file or with the javascript handling it, but I don't know how to check it and where to look.

### PR DESCRIPTION
**Pull request by mxposed**
Fixes #183

### CODE REVIEW

**Comment by maximilianh** [comment]
Oh man, I was trying to fix this yesterday but couldn't find it. In the end I moved the covid-airways dataset back to .tsv.gz Thsi is so much better. Many thanks!

**Comment by maximilianh** [comment]
Oh and now I understand that if numpy is not installed, the bug doesn't appear. I wonder if in exprEncode(), where I run exprArr.tobytes() I shouldn't also force a 32bit float or abort if the type is not 32bit, instead of just using whatever array was supplied to the function. with Javascript, 64bit floats should never be allowed as input...

**Comment by mxposed** [comment]
It sounds like a good idea, ensuring type before writing it in `exprEncode`.
And in this solution, I totally forgot about int matrices, and I expect numpy to be installed

**Comment by maximilianh** [comment]
So, many thanks for this change, staring more at this code made me realize
how poorly written this was. I totally forgot that ints are not necessarily
uint32.

I guess if this ever worked, it must have been by accident? I removed your
change and instead put it into exprEncode (the function that converts a
gene expression vector to a byte string). It now forces values to be either
uint32 or float32. It must have used originally int64, as numpy defaults to
that, which is why I don't know how it ever could have worked before with
integers...

**Pull request merged**
