### PR TITLE
Change label font

### PR DESCRIPTION
**Pull request by mxposed**
Custom font for labels with a preloader div in main html (a bit dirty…)
The font files are originally from google fonts

### CODE REVIEW

**Comment by maximilianh** [comment]
@matthewspeir didn't like the font a lot... Hey Matt, any other ideas on the font issue?

**Comment by matthewspeir** [comment]
I'm a little torn. I think this new font is great when zoomed out and looking at large regions (better than the old font), however, when you start to zoom on a single cluster (e.g. AT1) or further it starts to look a little weird. Like it's getting smaller than it should. Not really sure how to describe it.

**Comment by maximilianh** [comment]
Hmmm.... the font shouldn't' zoom at al. Usually the font is just placed at
a fixed size. The size shouldn't change...

>

**Comment by mxposed** [comment]
This font might not be ideal, but I guess it's still a good idea to move from default bold sans-serif. I can take any other font from Google fonts and put it in this pull request or even try to make it configurable.
As for zoom: fonts do not zoom, they stay at fixed size, but I get what you mean @matthewspeir

**Comment by maximilianh** [comment]
I agree that anything is better than the default font, in bold.

It’s getting smaller than it should ?

**Comment by matthewspeir** [comment]
Oh yeah, I didn't think the font itself was zooming, it's more that when you zoom in something about the font feels off in comparison to the old one. 

Either way, I would say just merge this in. We can always change the font again if others complain

Here are a couple of images comparing what the font looks like when you've zoomed in:
cellbrowserOldFont
cellbrowserNewFont

**Comment by maximilianh** [comment]
Ahh! I see what you mean Matt! 

So the new font is better, we all agree on that, but it's hard to see on darker background. I think this is because a) the font is thinner and b) Nikolai removed the drop shadow. The drop shadow was there to make the font stand out on dark background. Dark background is only there a lot when you zoom in.

Hey Nikolai, why did you remove the drop shadow? 

Did you try to  make the font a bit bigger or thicker to make it stand out more?

**Comment by mxposed** [comment]
I thought that the `strokeStyle` was already providing the same thing as text shadow, so I removed it. And I also tried to make it smaller. That's just how it felt to me.

I can restore text shadow and try other things too

**Comment by maximilianh** [comment]
Its similar to the shadow but since it’s thinner, I think it explains
Matt’s observation that on dark background it’s a lot harder to read...

**Pull request closed without merging**
