### PR TITLE
Sanitises initial underscores in field names

### PR DESCRIPTION
**Pull request by pcm32**
Aims to deal with #208

### CODE REVIEW

**Comment by pcm32** [comment]
Would it be possible to get a release after this is merged @maximilianh ? I have tested that with this fix our dataset works.

**Comment by maximilianh** [comment]
Oh interesting. this has never come up before. Thanks!

**Comment by nomadscientist** [comment]
Should this have fixed the UCSC browser issue?
I'm using this: (Galaxy Version 0.7.10+galaxy0). Still no luck...

**Comment by maximilianh** [comment]
We have not released yet, sorry.

**Comment by maximilianh** [comment]
The reason is an open bug in the violin plot display

**Comment by pcm32** [comment]
Hi @maximilianh, any chance for a release soon that includes this? Thanks!

**Comment by maximilianh** [comment]
Hi Pablo, another bug came up. I'm trying to get everything now, but just
in case: Would it be OK to do just a pip release? How important is the
violin plot feature for you?

**Comment by pcm32** [comment]
For us a pip release is fine, since that should trigger the bioconda auto bump. @nomadscientist is the violin plot bug relevant to what you need to show? Could you point us @maximilianh to a description of this bug to understand whether we can live without it or not? Thanks!

**Comment by matthewspeir** [comment]
@pcm32 Bug:

1. Go to our dev site: https://cells-test.gi.ucsc.edu/?ds=cortex-dev&gene=HES1 (coloring a plot by a gene)
2. Switch cursor to rectangle select
3. Select some cells
4. Notice that violin plot below legend doesn't appear

Compare this behavior with our main site: https://cells.ucsc.edu/?ds=cortex-dev&gene=HES1.

**Comment by maximilianh** [comment]
OK, the violin thing is fixed. Matt, can we live with the labels bug for
now? Or is that essential, too?

**Comment by matthewspeir** [comment]
No, I think we're good to go.

**Pull request merged**
