### PR TITLE
When computing markers, take top-n without dplyr, and with respect of p-value

### PR DESCRIPTION
**Pull request by mxposed**

### CODE REVIEW

**Comment by maximilianh** [comment]
Thanks!

**Comment by maximilianh** [comment]
On a sample file, I'm getting an error on this line:

Error in rep(NA, length(x) - markers.n) : invalid 'times' argument

Any idea why this could be?

**Comment by mxposed** [comment]
Oh, it might be because `markers.n` is bigger than the number of computed genes for the cluster `length(x)`?
It should really be `max(0, length(x) - markers.n)`

**Comment by maximilianh** [comment]
OK, I've changed this now.

Looking at this... just curious: why are you filling up the list with NAs...?

**Comment by maximilianh** [comment]
Also: is the ROC test the best for this? I've just changed it back to
wilcoxon, which seems a lot faster than ROC...
It could also be an option.

**Pull request merged**
