### PR TITLE
Fix access to obsm keys

### PR DESCRIPTION
**Pull request by ivirshup**
Reported in https://github.com/theislab/anndata/issues/181

`.obsm` and `varm` are no longer subclassed from arrays (now they are more like dicts, which was the intended interface) so getting the keys through `.dtype.names` no longer works. Access to the names through `.keys()` works, and should work for versions of anndata up to a year old.

### CODE REVIEW

**Comment by pcm32** [comment]
Will this change work with annData objects that are generated by older scanpy versions (1.3.x)? If that is not the case, could we make this change backwards compatible so that anndata objects generated by scanpy 1.3 will still work? Thanks!

**Comment by maximilianh** [comment]
Yes I was about to ask the same thing. I always try to stay backwards
compatible. I have a few changes in a branch where I tried to do that but
I’m sure Isaac knows much better every detail of the breaking changes that
anndata introduced recently. ( I’m unsure which concrete problem these
breaking changes solved, but that’s not really the topic of this ticket.)

**Comment by aditisk** [comment]
@ivirshup @maximilianh I am getting the as reported in theislab/anndata#181. I am using Scanpy v1.4.4, what can I do to avoid getting this error ? Thanks.

**Comment by maximilianh** [comment]
Sorry what do you mean with “I’m getting the as” ? Are you getting the same
error as in the other ticket ?

Thanks
Max

**Comment by aditisk** [comment]
Hi @maximilianh, sorry there was a typo. I meant I am getting the same error as the other ticket.

**Comment by maximilianh** [comment]
I think I committed code after Isaac's suggestion that included his code, but with a try-catch statement. This code is now in the current release and I hope this fixes the problem. @aditisk can you tell me if this is still a problem? Or maybe you have an anndata file where I can test if it works?

**Comment by maximilianh** [comment]
Hi @ivirshup many thanks for this fix and the PR. despite my long silence, it was very helpful to have your explanation. I took your commit and just wrapped a try/catch around it and fall back to the original solution, as Pablo was interested in staying compatible with scanpy 1.3 objects.

**Comment by maximilianh** [comment]
@aditisk  you can upgrade with "pip install cellbrowser --ugprade" and then upgrade your javascript code with "cbUpgrade -o htmlDirectory".

**Pull request merged**
