### PR TITLE
Add converter from Seurat object to cbBuild compatible tsv

### PR DESCRIPTION
**Pull request by mxposed**
Hi

This is a basic script to convert Seurat objects to tsv files compatible with `cbBuild`.
Please, let me know what you think, and what I should add to this to be more in line with `cbScanpy` for instance.
Also I would appreciate suggestions on how to handle `cellbrowser.conf`

### CODE REVIEW

**Comment by maximilianh** [comment]
Awesome!! Many thanks for this! I was just starting to work in it so this is perfect timing! I'll look into it next week.

**Comment by maximilianh** [comment]
This is great. Do you know how we could make a little library for R ? In this way, people could export their R objects directly from the R command line and wouldn't have to drop in the Linux command line. Is it enough just to create an R file and ask people to load it? Sorry, I'm not very good at R...

**Comment by mxposed** [comment]
Hi! I’ll look into creating a small library out of this script soon, will send you another pull request

**Comment by maximilianh** [comment]
Wow, many thanks!

**Comment by maximilianh** [comment]
Hi Nikolai, I would like to rename cbSeurat to something else, as I would
like to write a new program cbSeurat, that, like cbScanpy, takes an
expression matrix and runs it through a quick-and-dirty Seurat pipeline
based on the Seurat tutorial and creates the cellbrowser.conf file for it.
Is that OK with you? Do you have a preference on the name, e.g.
cbSeuratToTsv or cbSeuratImport or something like that?

**Comment by mxposed** [comment]
Hi. All right, sure, go ahead. I don't have any particular preference. I guess it would be logical if workflows for scanpy and seurat would be parallel

**Comment by maximilianh** [comment]
Hi, wait, before you spend time on this, shouldn't we add the Seurat folks
if they want to add your function to Seurat? That would be very useful...
then people wouldn't have to install anything!

**Comment by maximilianh** [comment]
You can create the pull request (which means you'll get the visibility and
attribution for what is your code) or I can do the pull request (if you're
busy at the moment) and point out that it really is your code and
acknowledge you in the cellbrowser docs.

**Comment by mxposed** [comment]
Great idea, I haven't thought about that. I'll ask Seurat folks

**Pull request merged**
